sudo: require
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov 90

script: 
  - bash coverage2.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash) -f LiteMath.h.gcov -t 56ae1d95-6267-4047-9a8e-ab8e19daddec
