name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: InstallQmake
      run : sudo apt-get install qmake 
    
    - name: AutoCodeCoverage
      working-directory: ${{github.workspace}}
      run: bash coverage2.sh

    - name: UploadCodeCoverage
      working-directory: ${{github.workspace}}
      run: bash <(curl -s https://codecov.io/bash) -f LiteMath.h.gcov
      
